# Generated by Django 4.2.3 on 2023-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_rename_social_media_contact_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
