# Generated by Django 4.2.3 on 2023-07-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_contact_instagram_contact_whatsapp_contact_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
