# Generated by Django 4.2.3 on 2023-07-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0005_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
