# Generated by Django 4.2.3 on 2023-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0007_branche_remove_contact_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='youtube',
        ),
        migrations.AddField(
            model_name='contact',
            name='beard_trim',
            field=models.FloatField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='haircut',
            field=models.FloatField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default=1, unique=True, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='razor_cut',
            field=models.FloatField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='shawes',
            field=models.FloatField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='starting',
            field=models.FloatField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='styling_color',
            field=models.FloatField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
