# Generated by Django 4.2.3 on 2023-07-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0009_remove_contact_beard_trim_remove_contact_haircut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='shawes',
            new_name='shaves',
        ),
        migrations.AlterField(
            model_name='price',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
