# Generated by Django 4.2.3 on 2023-07-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0010_rename_shawes_price_shaves_alter_price_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media')),
                ('service', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=6)),
            ],
        ),
    ]
