# Generated by Django 4.2.3 on 2023-07-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0012_barbers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Barbers',
            new_name='Barber',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
